version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: saiu_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: saiu_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d 

  backend:
    build: .
    container_name: saiu_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:rootpassword@db:3306/saiu_db
      - SECRET_KEY=tu_clave_secreta_super_segura_para_docker
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    depends_on:
      - db

volumes:
  mysql_data: